server:
  port: 80

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    gateway:
#      globalcors:
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins: "http://127.0.0.1:5500"
#            allowedHeaders: "*"
#            allowedMethods:
#              - POST
#              - GET
#              - PUT
#              - PATCH
#              - OPTIONS
#              - DELETE
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
      routes:
        - id: platform-service
          uri: lb://PLATFORM-SERVICE
          predicates:
            - Path=/
            - Method=GET
        - id: platform-service
          uri: lb://PLATFORM-SERVICE
          predicates:
            - Path=/platform-service/**
            - Method=GET
          filters:
            - RewritePath=/platform-service/(?<segment>.*), /$\{segment}
        - id: reply-service
          uri: lb://REPLY-SERVICE
          predicates:
            - Path=/reply-service/delete
            - Method=DELETE
          filters:
            - RewritePath=/reply-service/(?<segment>.*), /$\{segment}
            - name: AuthorizationFilter
        - id: reply-service
          uri: lb://REPLY-SERVICE
          predicates:
            - Path=/reply-service/update
            - Method=PUT
          filters:
            - RewritePath=/reply-service/(?<segment>.*), /$\{segment}
            - name: AuthorizationFilter
        - id: reply-service
          uri: lb://REPLY-SERVICE
          predicates:
            - Path=/reply-service/replies
            - Method=GET
          filters:
            - RewritePath=/reply-service/(?<segment>.*), /$\{segment}
        - id: reply-service
          uri: lb://REPLY-SERVICE
          predicates:
            - Path=/reply-service/save
            - Method=POST
          filters:
            - RewritePath=/reply-service/(?<segment>.*), /$\{segment}
            - name: AuthorizationFilter

#        comment-service
        - id: comment-service
          uri: lb://COMMENT-SERVICE
          predicates:
            - Path=/comment-service/update
            - Method=PUT
          filters:
            - RewritePath=/comment-service/(?<segment>.*), /$\{segment}
            - name: AuthorizationFilter
        - id: comment-service
          uri: lb://COMMENT-SERVICE
          predicates:
            - Path=/comment-service/delete
            - Method=DELETE
          filters:
            - RewritePath=/comment-service/(?<segment>.*), /$\{segment}
            - name: AuthorizationFilter
        - id: comment-service
          uri: lb://COMMENT-SERVICE
          predicates:
             - Path=/comment-service/getCommentList/**
             - Method=GET
          filters:
            - RewritePath=/comment-service/(?<segment>.*), /$\{segment}
        - id: comment-service
          uri: lb://COMMENT-SERVICE
          predicates:
            - Path=/comment-service/save
            - Method=POST
          filters:
            - RewritePath=/comment-service/(?<segment>.*), /$\{segment}
            - name: AuthorizationFilter
        - id: comment-service
          uri: lb://COMMENT-SERVICE
          predicates:
            - Path=/comment-service/actuator/**
            - Method=GET,POST
          filters:
            - RewritePath=/comment-service/(?<segment>.*), /$\{segment}

#---------game service----------
        - id: game-service
          uri: lb://GAME-SERVICE
          predicates:
            - Path=/game-service/lastSavedHistory
            - Method=GET
          filters:
            - RewritePath=/game-service/(?<segment>.*), /$\{segment}
        - id: game-service
          uri: lb://GAME-SERVICE
          predicates:
            - Path=/game-service/getPlayedGameList/**
            - Method=GET
          filters:
            - RewritePath=/game-service/(?<segment>.*), /$\{segment}
        - id: game-service
          uri: lb://GAME-SERVICE
          predicates:
            - Path=/game-service/loading
            - Method=GET
          filters:
            - RewritePath=/game-service/(?<segment>.*), /$\{segment}
        - id: game-service
          uri: lb://GAME-SERVICE
          predicates:
            - Path=/game-service/test
            - Method=GET
          filters:
            - RewritePath=/game-service/(?<segment>.*), /$\{segment}
        - id: game-service
          uri: lb://GAME-SERVICE
          predicates:
            - Path=/game-service/cardLibrary.json
            - Method=GET
          filters:
            - RewritePath=/game-service/(?<segment>.*), /$\{segment}
        - id: game-service
          uri: lb://GAME-SERVICE
          predicates:
            - Path=/game-service/main/**
            - Method=GET
          filters:
            - RewritePath=/game-service/(?<segment>.*), /$\{segment}
        - id: game-service
          uri: lb://GAME-SERVICE
          predicates:
            - Path=/game-service/main
            - Method=GET
          filters:
            - RewritePath=/game-service/(?<segment>.*), /$\{segment}
        - id: game-service
          uri: lb://GAME-SERVICE
          predicates:
            - Path=/game-service/getRecentlyPlayedGame/**
            - Method=GET
          filters:
            - RewritePath=/game-service/(?<segment>.*), /$\{segment}
        - id: game-service
          uri: lb://GAME-SERVICE
          predicates:
            - Path=/game-service/save
            - Method=POST
          filters:
            - RewritePath=/game-service/(?<segment>.*), /$\{segment}
        - id: game-service
          uri: lb://GAME-SERVICE
          predicates:
            - Path=/game-service/cardGame
            - Method=GET
          filters:
            - RewritePath=/game-service/(?<segment>.*), /$\{segment}
        - id: game-service
          uri: lb://GAME-SERVICE
          predicates:
            - Path=/game-service/actuator/**
            - Method=GET,POST
          filters:
            - RewritePath=/game-service/(?<segment>.*), /$\{segment}
        - id: game-service
          uri: lb://GAME-SERVICE
          predicates:
            - Path=/game-service/**
            - Method=GET
          filters:
            - RewritePath=/game-service/(?<segment>.*), /$\{segment}

#          user-service
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/myInfo
            - Method=GET
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/users
            - Method=GET
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/loginForm
            - Method=GET
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/registration
            - Method=GET
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/main
            - Method=GET
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/login
            - Method=POST
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/users
            - Method=POST
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
            - Method=GET
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/validateJwt
            - Method=GET
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/actuator/**
            - Method=GET,POST
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace, busrefresh, info, metrics, prometheus