server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka


spring:
  application:
    name: apigateway-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    gateway:
#      globalcors:
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins: "http://127.0.0.1:5500"
#            allowedHeaders: "*"
#            allowedMethods:
#              - POST
#              - GET
#              - PUT
#              - PATCH
#              - OPTIONS
#              - DELETE
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
      routes:
        - id: reply-service
          uri: lb://REPLY-SERVICE
          predicates:
            - Path=/reply-service/delete
            - Method=DELETE
          filters:
            #            - RemoveRequestHeader=Cookie
            - RewritePath=/reply-service/(?<segment>.*), /$\{segment}
            - name: AuthorizationFilter
        - id: reply-service
          uri: lb://REPLY-SERVICE
          predicates:
            - Path=/reply-service/update
            - Method=PUT
          filters:
            #            - RemoveRequestHeader=Cookie
            - RewritePath=/reply-service/(?<segment>.*), /$\{segment}
            - name: AuthorizationFilter
        - id: reply-service
          uri: lb://REPLY-SERVICE
          predicates:
            - Path=/reply-service/replies
            - Method=GET
          filters:
            #            - RemoveRequestHeader=Cookie
            - RewritePath=/reply-service/(?<segment>.*), /$\{segment}
        - id: reply-service
          uri: lb://REPLY-SERVICE
          predicates:
            - Path=/reply-service/save
            - Method=POST
          filters:
            #            - RemoveRequestHeader=Cookie
            - RewritePath=/reply-service/(?<segment>.*), /$\{segment}
            - name: AuthorizationFilter
#        comment-service
        - id: comment-service
          uri: lb://COMMENT-SERVICE
          predicates:
            - Path=/comment-service/update
            - Method=PUT
          filters:
            #            - RemoveRequestHeader=Cookie
            - RewritePath=/comment-service/(?<segment>.*), /$\{segment}
            - name: AuthorizationFilter
        - id: comment-service
          uri: lb://COMMENT-SERVICE
          predicates:
            - Path=/comment-service/delete
            - Method=DELETE
          filters:
            #            - RemoveRequestHeader=Cookie
            - RewritePath=/comment-service/(?<segment>.*), /$\{segment}
            - name: AuthorizationFilter
        - id: comment-service
          uri: lb://COMMENT-SERVICE
          predicates:
             - Path=/comment-service/getCommentList/**
             - Method=GET
          filters:
            #            - RemoveRequestHeader=Cookie
            - RewritePath=/comment-service/(?<segment>.*), /$\{segment}
        - id: comment-service
          uri: lb://COMMENT-SERVICE
          predicates:
            - Path=/comment-service/save
            - Method=POST
          filters:
#            - RemoveRequestHeader=Cookie
            - RewritePath=/comment-service/(?<segment>.*), /$\{segment}
            - name: AuthorizationFilter
        - id: comment-service
          uri: lb://COMMENT-SERVICE
          predicates:
            - Path=/comment-service/actuator/**
            - Method=GET,POST
          filters:
#            - RemoveRequestHeader=Cookie
            - RewritePath=/comment-service/(?<segment>.*), /$\{segment}

#              history service
        - id: history-service
          uri: lb://HISTORY-SERVICE
          predicates:
            - Path=/history-service/lastSavedHistory
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/history-service/(?<segment>.*), /$\{segment}
        - id: history-service
          uri: lb://HISTORY-SERVICE
          predicates:
            - Path=/history-service/getPlayedGameList/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/history-service/(?<segment>.*), /$\{segment}
        - id: history-service
          uri: lb://HISTORY-SERVICE
          predicates:
            - Path=/history-service/save
            - Method=POST
          filters:
            #            - RemoveRequestHeader=Cookie
            - RewritePath=/history-service/(?<segment>.*), /$\{segment}
        - id: history-service
          uri: lb://HISTORY-SERVICE
          predicates:
            - Path=/history-service/actuator/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/history-service/(?<segment>.*), /$\{segment}
#---------game service----------
        - id: game-service
          uri: lb://GAME-SERVICE
          predicates:
            - Path=/game-service/loading
            - Method=GET
          filters:
            #            - RemoveRequestHeader=Cookie
            - RewritePath=/game-service/(?<segment>.*), /$\{segment}
        - id: game-service
          uri: lb://GAME-SERVICE
          predicates:
            - Path=/game-service/test
            - Method=GET
          filters:
            #            - RemoveRequestHeader=Cookie
            - RewritePath=/game-service/(?<segment>.*), /$\{segment}
        - id: game-service
          uri: lb://GAME-SERVICE
          predicates:
            - Path=/game-service/cardLibrary.json
            - Method=GET
          filters:
            #            - RemoveRequestHeader=Cookie
            - RewritePath=/game-service/(?<segment>.*), /$\{segment}
        - id: game-service
          uri: lb://GAME-SERVICE
          predicates:
            - Path=/game-service/main/**
            - Method=GET
          filters:
            #            - RemoveRequestHeader=Cookie
            - RewritePath=/game-service/(?<segment>.*), /$\{segment}
        - id: game-service
          uri: lb://GAME-SERVICE
          predicates:
            - Path=/game-service/main
            - Method=GET
          filters:
            #            - RemoveRequestHeader=Cookie
            - RewritePath=/game-service/(?<segment>.*), /$\{segment}
        - id: game-service
          uri: lb://GAME-SERVICE
          predicates:
            - Path=/game-service/getRecentlyPlayedGame/**
            - Method=GET
          filters:
            #            - RemoveRequestHeader=Cookie
            - RewritePath=/game-service/(?<segment>.*), /$\{segment}
        - id: game-service
          uri: lb://GAME-SERVICE
          predicates:
            - Path=/game-service/save
            - Method=POST
          filters:
            #            - RemoveRequestHeader=Cookie
            - RewritePath=/game-service/(?<segment>.*), /$\{segment}
        - id: game-service
          uri: lb://GAME-SERVICE
          predicates:
            - Path=/game-service/cardGame
            - Method=GET
          filters:
#            - RemoveRequestHeader=Cookie
            - RewritePath=/game-service/(?<segment>.*), /$\{segment}
        - id: game-service
          uri: lb://GAME-SERVICE
          predicates:
            - Path=/game-service/actuator/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/game-service/(?<segment>.*), /$\{segment}
        - id: game-service
          uri: lb://GAME-SERVICE
          predicates:
            - Path=/game-service/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/game-service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/myInfo
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
#            - AuthorizationHeaderFilter
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/users
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/loginForm
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/registration
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/main
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/users
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
#            - AuthorizationHeaderFilter
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/validateJwt
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/actuator/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}




#bootstrap.yml 을 써서 외부 구성 파일을 사용하면 실행 순서만 우선순위가 아니라 중복 작성시 외부 구성파일이 우선으로 작동되는것인가 ?
#깜빡하고 여기 안지우고 돌렸지만 제대로 동작
#token:
#  secret: value1

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace, busrefresh, info, metrics, prometheus